name: recursive web_notes build

run-name: ${{ github.actor }} is building TFG notes

on: 
  push:
  workflow_dispatch:

jobs:

  build_notes:

    name: Building web notes from graph
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3     

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'      

      - name: Install Dependencies
        run: pip install -r requirements.txt   

      - name: Install Jupyter
        run: sudo -H pip install jupyter

      - name: Install Mermaid Converter
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Run Script and Build Notes
        run: |
          jupyter nbconvert --to script ./_k.pcs.zen/automate_md.ipynb
          python ./_k.pcs.zen/automate_md.py      
          
      - name: Commit and Push Changes
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push


# https://towardsdatascience.com/scheduling-notebook-and-script-runs-with-github-actions-cc60f3ac17f2
# https://stackoverflow.com/questions/64374179/how-to-push-to-another-repository-in-github-actions