name: ${{ github.actor }} recursive web_notes build:

on: [push]

workflow_dispatch:

jobs:

  build_notes:

    name: Building web notes from graph
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2      

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'      

      - name: Install Dependencies
        run: pip install -r requirements.txt   

      - name: Install Mermaid Converter
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Run Script and Build Notes
        run: |
          jupyter nbconvert --to script ./_k.pcs.zen/automate_md.ipynb
          python ./_k.pcs.zen/automate_md.py      
          
      # - name: Commit and Push Changes
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add weather_locations.csv weather_locations.png
      #     git commit -m "Updated plot on `date` with GitHub Actions"
      #     git push origin master


# https://towardsdatascience.com/scheduling-notebook-and-script-runs-with-github-actions-cc60f3ac17f2